// LinkedIn Post Analyzer - Background Service Worker
// Handles AI analysis and data storage

class PostAnalyzerService {
  constructor() {
    this.apiKey = null;
    this.postsDb = {};
    this.usersDb = {};
    this.init();
  }

  async init() {
    console.log('Post Analyzer Service initialized');
    
    // Load data from storage
    await this.loadData();
    
    // Set up message listeners
    chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
      this.handleMessage(request, sender, sendResponse);
      return true; // Keep channel open for async response
    });
  }

  async loadData() {
    const data = await chrome.storage.local.get(['apiKey', 'postsDb', 'usersDb']);
    this.apiKey = data.apiKey || null;
    this.postsDb = data.postsDb || {};
    this.usersDb = data.usersDb || {};
  }

  async saveData() {
    await chrome.storage.local.set({
      postsDb: this.postsDb,
      usersDb: this.usersDb
    });
  }

  handleMessage(request, sender, sendResponse) {
    switch (request.action) {
      case 'analyzePost':
        this.analyzePost(request.post).then(result => {
          sendResponse(result);
        }).catch(error => {
          sendResponse({ success: false, error: error.message });
        });
        break;
      
      case 'getStats':
        this.getStats().then(stats => {
          sendResponse({ success: true, stats });
        });
        break;
      
      case 'getUsers':
        this.getUsers().then(users => {
          sendResponse({ success: true, users });
        });
        break;
      
      case 'toggleUserFilter':
        this.toggleUserFilter(request.userId).then(() => {
          sendResponse({ success: true });
        });
        break;
      
      case 'setApiKey':
        this.setApiKey(request.apiKey).then(() => {
          sendResponse({ success: true });
        });
        break;
      
      case 'clearData':
        this.clearData().then(() => {
          sendResponse({ success: true });
        });
        break;
      
      default:
        sendResponse({ success: false, error: 'Unknown action' });
    }
  }

  async analyzePost(post) {
    try {
      // Check if already analyzed
      if (this.postsDb[post.id]) {
        return {
          success: true,
          aiScore: this.postsDb[post.id].aiScore,
          cached: true
        };
      }

      // Check if we have an API key
      if (!this.apiKey) {
        // Return a mock score if no API key is configured
        const mockScore = this.getMockAIScore(post.content);
        await this.storePost(post, mockScore);
        return { success: true, aiScore: mockScore, mock: true };
      }

      // Call OpenAI API
      const aiScore = await this.callOpenAI(post.content);
      
      // Store the result
      await this.storePost(post, aiScore);
      
      return { success: true, aiScore, mock: false };
    } catch (error) {
      console.error('Error analyzing post:', error);
      
      // Fallback to mock score on error
      const mockScore = this.getMockAIScore(post.content);
      await this.storePost(post, mockScore);
      
      return { success: true, aiScore: mockScore, mock: true, error: error.message };
    }
  }

  async callOpenAI(content) {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are an AI content detector. Analyze the following text and determine the likelihood it was generated by AI. Respond with only a number between 0 and 1, where 0 means definitely human-written and 1 means definitely AI-generated. Consider factors like: repetitive phrasing, generic language, perfect grammar, lack of personal anecdotes, corporate buzzwords, and formulaic structure.'
          },
          {
            role: 'user',
            content: content
          }
        ],
        temperature: 0.3,
        max_tokens: 10
      })
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    const scoreText = data.choices[0].message.content.trim();
    const score = parseFloat(scoreText);
    
    return isNaN(score) ? 0.5 : Math.max(0, Math.min(1, score));
  }

  getMockAIScore(content) {
    // Simple heuristic for demo purposes
    let score = 0;
    
    // Check for AI-like patterns
    const aiIndicators = [
      /\b(delve|utilize|leverage|synergy|paradigm|robust|cutting-edge)\b/gi,
      /\b(innovative|transformative|game-changing|revolutionary)\b/gi,
      /\b(it's important to note|it's worth mentioning|in conclusion)\b/gi,
      /\b(furthermore|moreover|additionally|consequently)\b/gi
    ];
    
    aiIndicators.forEach(pattern => {
      const matches = content.match(pattern);
      if (matches) {
        score += matches.length * 0.15;
      }
    });
    
    // Check for excessive emoji (can indicate automated posting)
    const emojiCount = (content.match(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}]/gu) || []).length;
    if (emojiCount > 5) score += 0.1;
    
    // Check for very formal structure
    if (content.includes('Dear') || content.includes('Best regards')) {
      score += 0.1;
    }
    
    // Normalize score
    return Math.max(0, Math.min(1, score));
  }

  async storePost(post, aiScore) {
    // Store post
    this.postsDb[post.id] = {
      ...post,
      aiScore,
      analyzedAt: new Date().toISOString()
    };
    
    // Update user statistics
    if (!this.usersDb[post.userId]) {
      this.usersDb[post.userId] = {
        userId: post.userId,
        userName: post.userName,
        userUrl: post.userUrl,
        postCount: 0,
        totalAIScore: 0,
        avgAIScore: 0,
        filtered: false,
        firstSeen: new Date().toISOString()
      };
    }
    
    const user = this.usersDb[post.userId];
    user.postCount++;
    user.totalAIScore += aiScore;
    user.avgAIScore = user.totalAIScore / user.postCount;
    user.userName = post.userName; // Update name in case it changed
    user.userUrl = post.userUrl;
    user.lastSeen = new Date().toISOString();
    
    await this.saveData();
  }

  async getStats() {
    const totalPosts = Object.keys(this.postsDb).length;
    const totalUsers = Object.keys(this.usersDb).length;
    
    let highAIPosts = 0;
    let mediumAIPosts = 0;
    let lowAIPosts = 0;
    
    Object.values(this.postsDb).forEach(post => {
      if (post.aiScore > 0.7) highAIPosts++;
      else if (post.aiScore > 0.4) mediumAIPosts++;
      else lowAIPosts++;
    });
    
    const filteredUsers = Object.values(this.usersDb).filter(u => u.filtered).length;
    
    return {
      totalPosts,
      totalUsers,
      highAIPosts,
      mediumAIPosts,
      lowAIPosts,
      filteredUsers
    };
  }

  async getUsers() {
    return Object.values(this.usersDb).sort((a, b) => b.avgAIScore - a.avgAIScore);
  }

  async toggleUserFilter(userId) {
    if (this.usersDb[userId]) {
      this.usersDb[userId].filtered = !this.usersDb[userId].filtered;
      
      // Update filteredUsers in storage for content script
      const filteredUsers = {};
      Object.values(this.usersDb).forEach(user => {
        if (user.filtered) {
          filteredUsers[user.userId] = true;
        }
      });
      
      await chrome.storage.local.set({ filteredUsers });
      await this.saveData();
      
      // Notify content script to refresh
      chrome.tabs.query({ url: 'https://www.linkedin.com/*' }, (tabs) => {
        tabs.forEach(tab => {
          chrome.tabs.sendMessage(tab.id, { action: 'refreshFilters' });
        });
      });
    }
  }

  async setApiKey(apiKey) {
    this.apiKey = apiKey;
    await chrome.storage.local.set({ apiKey });
  }

  async clearData() {
    this.postsDb = {};
    this.usersDb = {};
    await chrome.storage.local.clear();
  }
}

// Initialize the service
const service = new PostAnalyzerService();
